techies23/video-conference-zoom

includes/views/post-type/tpl-meeting-fields.php
- Change to have a field to show shortcode for meeting
=> Generate shortcode to use on other post and pages

includes/helpers.php
slight modification to show correct time formats - affects premium plugins.
=> Correct time formats

includes/admin/class-zvc-admin-post-type.php, includes/class-zvc-shortcodes.php
- Added new post meta for Meeting called `_meeting_field_start_date_utc`
- Queried in shortcode in UTC time as well.
=> Save Meeting Time in UTC and query accordingly

includes/Shortcodes/Helpers.php, includes/Shortcodes/Recordings.php, includes/api/class-zvc-zoom-api-v2.php, templates/shortcode/zoom-recordings-by-meeting.php
[Support Ticket](https://wordpress.org/support/topic/recordings-list-by-meeting/#post-13249119)
- get all recordings via UUID instead of meeting ID
=> Get All Recordings for Given Meeting

includes/helpers.php
01/03/2020 annd 1/3/2020 must now be two different techniques
=> case for no leading zeros using date_i18n

includes/api/class-zvc-zoom-api-v2.php
Agenda string can only be 2000 chars.
=> Validation for agenda

includes/admin/class-zvc-admin-meetings.php, includes/admin/class-zvc-admin-post-type.php, includes/api/class-zvc-zoom-api-v2.php, includes/views/post-type/tpl-meeting-fields.php
=> Added waiting room

templates/content-meeting.php
Zoom Webinar date displaying Incorrect on Archive Meeting Pages
=> Correction for archive page Zoom Webinars

includes/views/post-type/tpl-meeting-fields.php
=> 45 minutes instead of 40

includes/Shortcodes/Recordings.php
Filter added is vczapi_recordings_show_password.
If true returned - then password will be shown to user in recording list.
=> Show recording password, can be enabled with filter 

includes/admin/class-zvc-admin-post-type.php
- Fix: Video not showing for Chrome Browsers due to CORP policy enforced by chrome
=> Set CORP headers for chrome shareArrayBuffer issue

includes/Shortcodes/Recordings.php
- By default hide recording chats 
- Added filter to show chat file if anyone desires.
=> Recording chat

includes/Elementor/Widgets/EmbedMeetings.php, includes/Elementor/Widgets/MeetingList.php, includes/Elementor/Widgets/WebinarList.php
I have fixed the issue of going number to negative while adding id of author
=> min number set on elementor widgets

includes/Elementor/Widgets/MeetingHosts.php
$type was returning string value. but while checking condition it was checked as integer.
=> changed number to string

includes/Elementor/Widgets/MeetingByPostID.php
added option to select layout for the zoom meeting by id elementor widget, added option to hide details, description and countdown to same widget
=> added new controls to the zoom meeting by post id elementor widget 

docs/docs/CNAME, docs/docs/vczapi-pro.md
- Added CNAME file to prevent reconfiguring every time you change documentation
- VCZAPI Pro documentaiton updated for calendar widget
=> CNAME, v1.7.9 VCZAPI Pro

includes/views/tabs/connect.php
- Removed verified S2SOAuth
- Removed duplicate class attribute
=> Verification for issues

includes/admin/class-zvc-admin-webinars.php
- Corrected option where Auto Recording option was not working with Webinars
=> Auto recording was not being set for webinars

README.txt, includes/Bootstrap.php, includes/Marketplace.php, video-conferencing-with-zoom-api.php
- Updated tested version to WP 6.7.1
- Marketplace settings updated
=> Tested up to WordPress 6.7.1

includes/Requests/Zoom.php, includes/api/class-zvc-zoom-api-v2.php, includes/views/live/tpl-list-recordings.php
Solves issue for double encoding issues that are created for some meeting UUIDs
=> Recordings UUID needs to check for / and needs double encoding
